package com.luisppb16.dbseed.config;

import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.components.PersistentStateComponent;
import com.intellij.openapi.components.State;
import com.intellij.openapi.components.Storage;
import com.intellij.util.xmlb.XmlSerializerUtil;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

@State(
    name = "com.luisppb16.dbseed.config.DbSeedSettingsState",
    storages = @Storage("DbSeedPlugin.xml"))
public class DbSeedSettingsState implements PersistentStateComponent<DbSeedSettingsState> {

  private static final String DEFAULT_OUTPUT_DIRECTORY = "src/main/resources/db/seeder";
  private static final UuidStrategy DEFAULT_UUID_STRATEGY = UuidStrategy.FUNCTION_CALL;
  private static final int DEFAULT_COLUMN_SPINNER_STEP = 3;

  public int columnSpinnerStep = DEFAULT_COLUMN_SPINNER_STEP;
  public String defaultOutputDirectory = DEFAULT_OUTPUT_DIRECTORY;
  public UuidStrategy uuidStrategy = DEFAULT_UUID_STRATEGY;

  public static DbSeedSettingsState getInstance() {
    return Objects.requireNonNull(
        ApplicationManager.getApplication().getService(DbSeedSettingsState.class),
        "DbSeedSettingsState service not found. Plugin might be improperly installed.");
  }

  @Nullable
  @Override
  public DbSeedSettingsState getState() {
    return this;
  }

  @Override
  public void loadState(@NotNull final DbSeedSettingsState state) {
    XmlSerializerUtil.copyBean(state, this);

    // Ensure resilience against null or invalid values from a deserialized state
    defaultOutputDirectory =
        Objects.requireNonNullElse(defaultOutputDirectory, DEFAULT_OUTPUT_DIRECTORY);
    uuidStrategy = Objects.requireNonNullElse(uuidStrategy, DEFAULT_UUID_STRATEGY);
    if (columnSpinnerStep <= 0) {
      columnSpinnerStep = DEFAULT_COLUMN_SPINNER_STEP;
    }
  }

  /** Defines the strategy for generating UUID values in the seed script. */
  public enum UuidStrategy {
    /**
     * Generates a database-specific function call (e.g., UUID(), gen_random_uuid()). The actual
     * UUID is generated by the database at insertion time.
     */
    FUNCTION_CALL,
    /**
     * Generates a random UUID (e.g., "550e8400-e29b-41d4-a716-446655440000") directly in the
     * script. The value is pre-generated by the plugin.
     */
    PRE_GENERATED
  }
}
