services:
  postgresql:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/schema_Postgres.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - db_net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb/schema_MySQL.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - db_net

  sqlite:
    image: keinos/sqlite3:latest
    container_name: sqlite
    restart: unless-stopped
    user: root
    volumes:
      - ./initdb/schema_SQLite.sql:/tmp/schema.sql
      - sqlite_data:/var/lib/sqlite
    entrypoint: ""
    command: >
      sh -c 'if [ ! -f /var/lib/sqlite/.initialized ]; then
        sqlite3 /var/lib/sqlite/test.db < /tmp/schema.sql &&
        touch /var/lib/sqlite/.initialized;
      fi &&
      chmod -R 777 /var/lib/sqlite &&
      tail -f /dev/null'
    networks:
      - db_net

volumes:
  postgres_data: { }
  mysql_data: { }
  sqlite_data: { }

networks:
  db_net:
    driver: bridge