#
# ******************************************************************************
# Copyright (c)  2026 Luis Paolo Pepe Barra (@LuisPPB16).
# All rights reserved.
# ******************************************************************************
#
quoteChar=[
closeQuoteChar=]
quoteEscape=]]
uppercaseIdentifiers=false
booleanTrue=1
booleanFalse=0
beginTransaction=BEGIN TRANSACTION;\n
commitTransaction=COMMIT TRANSACTION;\n
disableConstraints=DECLARE @sql NVARCHAR(MAX) = N'';\nSELECT @sql += N'ALTER TABLE ' + QUOTENAME(s.name) + N'.' + QUOTENAME(t.name) + N' NOCHECK CONSTRAINT ALL; '\nFROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id;\nEXEC sp_executesql @sql;\n
enableConstraints=DECLARE @sql NVARCHAR(MAX) = N'';\nSELECT @sql += N'ALTER TABLE ' + QUOTENAME(s.name) + N'.' + QUOTENAME(t.name) + N' WITH CHECK CHECK CONSTRAINT ALL; '\nFROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id;\nEXEC sp_executesql @sql;\n
dateFormat='${value}'
timestampFormat='${value}'
uuidFormat='${value}'
maxBatchSize=1000
supportsMultiRowInsert=true
batchHeader=INSERT INTO ${table} (${columns}) VALUES\n
batchRowPrefix=(
batchRowSuffix=)
batchRowSeparator=,\n
batchFooter=;\n
statementSeparator=;\n
